### ISSUE TITLE
How to we can structure the repository to share katas in different programming languages?

### ISSUE THREAD

**Issue by tonilopezmr** [CloudCoders/Katas#2]
The main idea is be able to share and execute different programming languages, like kotlin, swift, java..

How @JoseLlorensRipolles  @ConradoMateu ??

**Comment by ConradoMateu** [comment]
We can split the project in different Brands one per Each Programming language

**Comment by tonilopezmr** [comment]
Yes I have thought that, one calls master-java and master-swift?

**Comment by ConradoMateu** [comment]
Let's do it!

**Comment by tonilopezmr** [comment]
I'm adding a gradle and continuous integration

**Comment by tonilopezmr** [comment]
Okey @ConradoMateu all it's right! `master` branch has been deleted

**Comment by JoseLlorensRipolles** [comment]
That sound great! Let's go!

**Comment by tonilopezmr** [comment]
Okey finally @ConradoMateu has created master-java and master-swift, please pull the repo.

**Comment by tonilopezmr** [comment]
Hey I have restructure the project for more katas visibility.

@ConradoMateu you can do the same with xcode in master-swift
